In [ ]:
import numpy as np

Código para realizar operaciones elementales por renglones.

In [ ]:
5**2

25

In [ ]:
def Vale(x,n):
  y = x**n
  return y

In [ ]:
Vale(9.2,3)

778.6879999999999

In [ ]:
6 % 2

0

In [ ]:
# loops ciclos
indice = [1, 2, 3, 4, 5]

pares = [x for x in indice if x%2==0]

pares

[2, 4]

In [ ]:
[x for x in range(1,6)]

[1, 2, 3, 4, 5]

### Coefientes de una matriz: acceso en numpy

In [ ]:
A = np.array([[2, 1, 0.5], [1, 0 ,0 ], [2, 1, 0], [5, -1, 3] ] )

A

array([[ 2. ,  1. ,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [ ]:
A.shape

(4, 3)

In [ ]:
indice

[1, 2, 3, 4, 5]

In [ ]:
# La indexación en Python comienza en 0

print(indice[0])
print(indice[4])

1
5


In [ ]:
A.shape[0] # número de columnas de la matriz A

4

In [ ]:
A.shape[1] # número de renglones de la matriz A

3

In [ ]:
A

array([[ 2. ,  1. ,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [ ]:
A[0] # primer renglón

array([2. , 1. , 0.5])

In [ ]:
A[3][1]

-1.0

In [ ]:
B = np.copy(A)
B

array([[ 2. ,  1. ,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [ ]:
def RowSwap(A,k,l):
# =============================================================================
#     A  NumPy array.  RowSwap devolverá una matriz duplicada con filas
# k y l intercambiados.
# =============================================================================
    m = A.shape[0]  # m renglones
    n = A.shape[1]  # n columnas

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A NumPy array.  RowScale devolverá una matriz duplicada con el
# entradas de la fila k multiplicadas por escala..
# =============================================================================
    m = A.shape[0]  # m renglones
    n = A.shape[1]  # n columnas

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A numpy array.  RowAdd devolverá matriz duplicada con fila
# l modificado. Los nuevos valores serán los valores antiguos de la fila l agregados a
# los valores de la fila k, multiplicados por la escala.
# =============================================================================
    m = A.shape[0]  # m renglones
    n = A.shape[1]  # n columnas

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B


In [ ]:
A

array([[ 2. ,  1. ,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [ ]:
RowSwap(A,0,1)

array([[ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0.5],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [ ]:
RowScale(A, 0, 0.5)

array([[ 1.  ,  0.5 ,  0.25],
       [ 1.  ,  0.  ,  0.  ],
       [ 2.  ,  1.  ,  0.  ],
       [ 5.  , -1.  ,  3.  ]])

In [ ]:
A

array([[ 2. ,  1. ,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])

In [ ]:
RowAdd(A, 0, 1, 2)

array([[ 2. ,  1. ,  0.5],
       [ 5. ,  2. ,  1. ],
       [ 2. ,  1. ,  0. ],
       [ 5. , -1. ,  3. ]])