# Álgebra Lineal con Python

Recordemos que si damos $n\times m$ números reales, entonces podemos crear un arreglo (una matriz):
$$A_{m\times n}=\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}$$

y al conjunto de matrices con coeficientes en $\mathbb{R}$ lo denotamos $\text{Mat}_{m\times n}(\mathbb{R})$.


In [1]:
type(2), type(2.0), type("2") # La función type(obj) nos dice el tipo de objeto con el que se está trabajando.

(int, float, str)

### Variables
$$\text{nombre} = \text{objeto}$$

Debug: $\text{print(variable)}$

1. Suma de matrices

$$\begin{pmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{pmatrix} + \begin{pmatrix} b_{11} & b_{12} & \cdots & b_{1n} \\ b_{21} & b_{22} & \cdots & b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ b_{m1} & b_{m2} & \cdots & b_{mn} \end{pmatrix} = \begin{pmatrix} a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n} \\ a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn} \end{pmatrix}$$

2. Multiplicación de matrices

$$\begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix} \times \begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{pmatrix} = \begin{pmatrix} a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\ a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22} \end{pmatrix} $$

In [2]:
variable = "Hola"

x = 5

Cesar = {1, 2, "perro"}

print(variable)

print(x)


Hola
5


In [3]:
variable + str(x)

'Hola5'

### Listas

$L=[a_{0}, a_{1}, \dots, a_{n-1}]$

In [4]:
L = [1, 2, 3, 4, 5]

M = [6, 7, 8, 9 , 10]

N = [11, 12, 13]

print(L)
print(M)  # me muestra el resultado
print(N)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[11, 12, 13]


In [5]:
type(L)

list

In [6]:
L_set = set(L)

L_set

{1, 2, 3, 4, 5}

In [7]:
L_lista = list(L_set)
L_lista

[1, 2, 3, 4, 5]

In [8]:
L + M # concatena (no realiza operaciones vectoriales).

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
L + M + N

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

### NumPy

- Un vector = arreglo 1D en Python
- Una matriz = arreglo 2D en Python

In [10]:
import numpy as np

In [11]:
L_vector = np.array(L) # Convertir una lista en un vector. La funcion np.array, es la que te termina haciendo la operacion para el proceso.

L_vector

array([1, 2, 3, 4, 5])

In [12]:
type(L_vector)

numpy.ndarray

In [13]:
# Aqui se hace conversiones de listas a vectores.
M_vector = np.array(M)

N_vector = np.array(N)

print(M_vector)
print(N_vector)

[ 6  7  8  9 10]
[11 12 13]


In [14]:
# Aqui son el numero de elementos que tiene cada vector
len(L_vector), len(M_vector), len(N_vector)

(5, 5, 3)

# gracias a esto, ya podemos sumar vectores.


In [15]:
L_vector + M_vector # suma vectorial

array([ 7,  9, 11, 13, 15])

## Creando matrices con NumPy: El método `solve( , )`




Un cine vende boletos para adultos y para niños. Un boleto para adultos cuesta \$100, y un boleto para niños cuesta \$50. En una función, se vendieron un total de 120 boletos y se recaudaron \$8,000. ¿Cuántos boletos de cada tipo se vendieron?

{Planteamiento del sistema de ecuaciones}

Sea \(x\) el número de boletos para adultos y \(y\) el número de boletos para niños.


La primera ecuación se basa en el total de boletos vendidos:
    \[
    x + y = 120
    \]
    La segunda ecuación se basa en el total de dinero recaudado:
    \[
    100x + 50y = 8000
    \]


\[
\begin{aligned}
1. & \quad x + y = 120 \\
2. & \quad 100x + 50y = 8000
\end{aligned}
\]


#vamos a resolver este problema usando numpy

In [16]:
#escribimos la matriz asociada al sistema de ecuaciones
A = np.array([1, 1, 100, 50]).reshape((2,2)) #el reshape, va a convertir esta matriz en una de 2x2
A

array([[  1,   1],
       [100,  50]])

In [17]:
B = np.array([200,2400])

$$AX=B$$

#numpy tiene una sublibreria que se llama linalg en donde se pueden resolver sistemas de ecuaciones

In [18]:
#la funcion solve, resuleve el sistema de ecuaciones
X = np.linalg.solve(A,B)

X

array([-152.,  352.])

La solucion al sistema de ecuaciones es:
x=-152
y=352